[main]
# ---------------
# HTML DOWNLOADER
# ---------------

# Digunakan crawler.py. Jika tidak ditetapkan maka akan dibuat direktori "tmp"
# di home.
;base_download_dir = /home/sugiana/tmp

# Digunakan downloader.py berisi daftar tautan produk sesuai kategori. Jika di
# antaranya memuat produk lain seperti plastik bubble atau kotak kayu maka akan
# ditetapkan oleh AI sebagai kategori "lainnya". Jadi tidak masalah tercampur.
# Sifatnya wajib.
url =
    https://www.tokopedia.com/gigabyteofficial/etalase/nvidia-gpu
    https://www.tokopedia.com/gigabyteofficial/etalase/radeon-gpu
    https://www.tokopedia.com/asus-official-store-891/etalase/vga
    https://www.tokopedia.com/msi-id/etalase/nvidia-gpu
    https://www.tokopedia.com/aofficial-14/etalase/vga-asrock-radeon
    https://www.tokopedia.com/aofficial-14/etalase/vga-asrock-intel-arc
    https://www.tokopedia.com/biostarsme/etalase/biostar-vga
    https://www.tokopedia.com/nvidiageforce/etalase/geforce-rtx-3050-6gb-new
    https://www.tokopedia.com/nvidiageforce/etalase/geforce-rtx-50-series
    https://www.tokopedia.com/nanokomputer/etalase/geforce-rtx-50-series
    https://www.tokopedia.com/nanokomputer/etalase/geforce-rtx-40-series
    https://www.tokopedia.com/nanokomputer/etalase/geforce-rtx-30-series
    https://www.tokopedia.com/nanokomputer/etalase/geforce-gtx-and-below
    https://www.tokopedia.com/nanokomputer/etalase/nvidia-rtx-quadro-series
    https://www.tokopedia.com/nanokomputer/etalase/radeon-rx-9000-series
    https://www.tokopedia.com/nanokomputer/etalase/radeon-rx-7000-series
    https://www.tokopedia.com/nanokomputer/etalase/radeon-rx-6000-series
    https://www.tokopedia.com/nanokomputer/etalase/intel-arc-gpu
    https://www.tokopedia.com/enterkomputer/etalase/vga-nvidia-geforce
    https://www.tokopedia.com/enterkomputer/etalase/vga-amd-radeon
    https://www.tokopedia.com/enterkomputer/etalase/geforce-rtx-30-series
    https://www.tokopedia.com/enterkomputer/etalase/geforce-gtx-16-series


# ------------
# AKAL IMITASI
# ------------

# - Prompt -

# Digunakan to_category.py untuk menetapkan prompt_template di bawah sebagai 
# kategori apa. Jika jawaban AI terdaftar maka field category akan diisi dengan
# nilai pertama yaitu "gpu".
# Sifatnya wajib.
category = gpu, graphic adapter

# Hanya tanya ke AI bila sesuai filter. Selain itu akan ditetapkan ke kategori
# "lainnya". Filter ini digunakan oleh DataFrame.query().
# Bila di filter ditemukan "stock > 0" maka downloader.py hanya akan membaca
# yang ada stoknya saja.
# Sifatnya tidak wajib.
filter = stock > 0

# {desc} akan diganti dengan gabungan field title dan description.
# Sifatnya wajib.
prompt_template =
    Berikut ini spesifikasi hardware.

    {desc}

    Jawab pertanyaan berikut dalam bentuk JSON dictionary sesuai nomor urut.

    {columns}


# Nama kolom dan pertanyaan untuk AI. Rangkaian ini akan disematkan di
# {columns} pada prompt_template di atas.
# Sifatnya wajib.
columns =
    category: Apakah ini sebuah graphic adapter atau lainnya ? Jawab singkat.
    brand_name: Apa mereknya ? Satu kata saja.
    processor_name: Apa merek prosesornya ? Satu kata saja.
    processor_type: Apa tipe prosesornya ?
    memory_gb: Berapa gigabyte memorinya ? Sebut angka saja.
    pcie_version: PCIe versi berapa ? Sebut angka saja.
    power_watt: Berapa watt ? Sebut angka saja.


# ---------
# repair.py
# ---------

# Sebuah GPU wajib ada informasi merek prosesor. Jika tidak ada maka akan
# ditetapkan sebagai kategori "lainnya".
# Sifatnya tidak wajib.
not_null_columns =
    processor_name


# - Numeric -

# Jika nama kolom berakhiran underscore ( _ ) ditambah numeric unit (contoh:
# memory_gb) maka nilainya akan diuji dengan fungsi float(). Jika gagal maka
# diganti dengan None. 
# Sifatnya tidak wajib.
numeric_units =
    gb
    version
    watt


# Jika nilainya di luar batas maka akan dikosongkan
range_values =
    memory_gb:1,64
    pcie_version:1,5


# --------
# check.py
# --------

# Daftar kolom yang akan dihitung jumlah produknya:
# SELECT column, count(*) FROM ... GROUP BY 1
count_columns =
    brand_name
    processor_name
    memory_gb
    pcie_version


# Daftar kolom yang akan dihitung nilai minimum dan maksimumnya:
# SELECT column, min(column), max(column) FROM ... GROUP BY 1
min_max_columns =
    memory_gb
    pcie_version
    price


# - Name -

# Nama kolom yang berakhiran "_name" nilainya akan dicek berdasarkan daftar
# ini. Misalkan AI menetapkan brand_name = GeForce maka repair.py mengubahnya
# menjadi NVIDIA. Ia juga peduli huruf kecil dan besar. Jadi bila AI bilang
# brand_name = GIGABYTE maka akan diubah menjadi Gigabyte. Untuk ASUS tidak berubah
# sesuai yang terdaftar.

[brand_name]
ASUS =
Gigabyte =
NVIDIA =
    GeForce
    RTX


[processor_name]
AMD =
    Radeon
    Ryzen
NVIDIA =
    GeForce
