[main]
base_download_dir = /home/sugiana/tmp

url =
    https://www.tokopedia.com/gigabyteofficial/product
    https://www.tokopedia.com/asus-component/product
    https://www.tokopedia.com/msi-id/product
    https://www.tokopedia.com/aofficial-14/product
    https://www.tokopedia.com/biostarsme/etalase/biostar-mb


# ------------
# AKAL IMITASI
# ------------

# Hal AI digunakan oleh to_category.py.

# Ini adalah "system prompt" yang mengawali "user prompt". Saat ini hanya
# digunakan oleh Ollama.
role =
    Kamu adalah seorang yang pendiam. Jawabanmu selalu singkat dan tanpa
    asesoris kata seperti tambahan 2 karakter bintang ( ** ) untuk menebalkan,
    dan sejenisnya


# - AI: Ollama -

# Digunakan to_category.py, berisi tautan web service Ollama
ollama_url = http://localhost:11434

# Model Ollama yang digunakan. Daftarnya bisa lihat dengan perintah "ollama list".
ollama_model = gemma2


# - AI: Gemini -

# Tautan web service Gemini. Jika ini aktif maka konfigurasi Ollama diabaikan.
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-thinking-exp-01-21:generateContent?key=YOUR-API-KEY


# - Prompt -

# Digunakan to_category.py untuk menetapkan prompt_template di bawah sebagai 
# kategori apa. Jika pertanyaan pertama dijawab "tidak" maka category diisi
# dengan "lainnya".

category = gpu 

prompt_template =
    Berikut ini diduga spesifikasi graphic adapter.

    {desc}

    Jawab pertanyaan berikut dalam bentuk JSON dictionary sesuai nomor urut.
    Jangan ada karakter apapun setelah JSON.

    1. Apakah ini sebuah graphic adapter ? Jawab "ya" atau "bukan".

    Jika "ya" maka lanjut jawab ini:

    2. Apa mereknya ? Satu kata saja.
    3. Apa merek prosesornya ? Satu kata saja.
    4. Apa tipe prosesornya ? Singkat saja.
    5. Berapa gigabyte memorinya ? Sebut angka saja.
    6. PCIe versi berapa ? Sebut angka saja.


columns =
    category
    brand
    processor_brand
    processor_type
    memory_gb
    pcie_version


numeric_units =
    gb
    version


# --------
# check.py
# --------

# Daftar kolom yang akan dihitung jumlah produknya:
# SELECT column, count(*) FROM ... GROUP BY 1
count_columns =
    brand
    processor_brand
    memory_gb
    pcie_version


# Daftar kolom yang akan dihitung nilai minimum dan maksimumnya:
# SELECT column, min(column), max(column) FROM ... GROUP BY 1
min_max_columns =
    memory_gb
    pcie_version
    price


[brand]
ASRock =
ASUS =
Biostar =
Gigabyte =
MSI =
NVIDIA =
    GeForce


[processor_brand]
AMD =
    Radeon
    Ryzen
Intel =
NVIDIA =
    GeForce
