[main]
category = hp 
base_download_dir = /home/sugiana/tmp
ollama_url = http://localhost:11434
ollama_model = gemma2

# gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent 
# gemini_key = YOUR-API-KEY

url =
    https://www.tokopedia.com/oppo/product
    https://www.tokopedia.com/samsung/etalase/mobiles
    https://www.tokopedia.com/officialinfinix/product
    https://www.tokopedia.com/xiaomi/etalase/mobile
    https://www.tokopedia.com/realme/product
    https://www.tokopedia.com/vivo/product
    https://www.tokopedia.com/asus-mobile
    https://www.tokopedia.com/huawei/etalase/smartphone
    https://www.tokopedia.com/nokia-mobile/product
    https://www.tokopedia.com/nerdbossgadget/product
