[main]
# ---------------
# HTML DOWNLOADER
# ---------------

# Digunakan crawler.py. Jika tidak ditetapkan maka akan dibuat direktori "tmp"
# di home.
;base_download_dir = /home/sugiana/tmp

# Digunakan downloader.py berisi daftar tautan produk sesuai kategori. Jika di
# antaranya memuat produk lain seperti plastik bubble atau kotak kayu maka akan
# ditetapkan oleh AI sebagai kategori "lainnya". Jadi tidak masalah tercampur.
# Sifatnya wajib.
url =
    https://www.tokopedia.com/nvidiageforcelt/product
    https://www.tokopedia.com/nvidiageforce/etalase/laptop-colorful-evol-series
    https://www.tokopedia.com/lenovo-official/etalase/ideapad-notebook
    https://www.tokopedia.com/lenovo-official/etalase/yoga-notebook
    https://www.tokopedia.com/lenovo-official/etalase/loq-series
    https://www.tokopedia.com/lenovo-official/etalase/lenovo-v-series-k-series
    https://www.tokopedia.com/lenovo-official/etalase/thinkbook-notebook
    https://www.tokopedia.com/lenovo-official/etalase/legion-series
    https://www.tokopedia.com/lenovo-official/etalase/thinkpad-notebook
    https://www.tokopedia.com/dell-premium-official/etalase/laptop-dell-inspiron
    https://www.tokopedia.com/dell-premium-official/etalase/laptop-dell-xps
    https://www.tokopedia.com/dell-premium-official/etalase/laptop-dell-latitude
    https://www.tokopedia.com/asus/etalase/asus-oled-series
    https://www.tokopedia.com/asus/etalase/asus-creator-series
    https://www.tokopedia.com/asus/etalase/asus-zenbook-series
    https://www.tokopedia.com/asus/etalase/asus-vivobook-series
    https://www.tokopedia.com/asus/etalase/asus-rog-gaming-series
    https://www.tokopedia.com/asus/etalase/asus-tuf-gaming-series
    https://macstore.id/product-category/macbook
    https://www.tokopedia.com/msi-indonesia/product
    https://www.tokopedia.com/hp/etalase/semua-laptop
    https://www.tokopedia.com/acer-jakarta/etalase/acer-aspire-series
    https://www.tokopedia.com/acer-jakarta/etalase/acer-aspire-lite-series
    https://www.tokopedia.com/acer-jakarta/etalase/acer-lite-series
    https://www.tokopedia.com/acer-jakarta/etalase/acer-aspire-go
    https://www.tokopedia.com/acer-jakarta/etalase/acer-swift-go-ai
    https://www.tokopedia.com/acer-jakarta/etalase/acer-swift-series
    https://www.tokopedia.com/acer-jakarta/etalase/acer-spin-series
    https://www.tokopedia.com/acer-jakarta/etalase/acer-nitro-series
    https://www.tokopedia.com/axioo-indonesia/etalase/hype-series
    https://www.tokopedia.com/axioo-indonesia/etalase/z-series
    https://www.tokopedia.com/zyrex/etalase/intel-series
    https://www.tokopedia.com/zyrex/etalase/amd-series
    https://www.tokopedia.com/zyrex/etalase/laptop-maveric
    https://www.tokopedia.com/zyrex/etalase/laptop-consumer
    https://www.tokopedia.com/zyrex/etalase/zyrex-2in-1
    https://www.tokopedia.com/zyrex/etalase/laptop-notebook
    https://www.tokopedia.com/glorycomputerr/product
    https://www.tokopedia.com/advanstore/etalase/laptop
    https://www.tokopedia.com/tecnoofficialstore/etalase/aiot-products


# ------------
# AKAL IMITASI
# ------------

# Hal AI digunakan oleh to_category.py.

# Ini adalah "system prompt" yang mengawali "user prompt". Tujuannya untuk
# mendapatkan jawaban yang lebih tepat. Saat ini hanya digunakan oleh Ollama.
# Sifatnya tidak wajib.
;role =
;    Kamu adalah seorang yang pendiam. Jawabanmu selalu singkat dan tanpa
;    asesoris kata seperti tambahan 2 karakter bintang ( ** ) untuk menebalkan,
;    dan sejenisnya


# - AI: Ollama -

# Digunakan to_category.py, berisi tautan web service Ollama.
# Sifatnya tidak wajib jika gemini_url aktif.
ollama_url = http://localhost:11434/api/chat

# Model Ollama yang digunakan. Daftarnya bisa lihat dengan perintah "ollama list".
# Sifatnya wajib jika ollama_url aktif.
ollama_model = gemma2


# - AI: Gemini -

# Tautan web service Gemini. Jika ini aktif maka ollama_url diabaikan.
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-thinking-exp-01-21:generateContent?key=YOUR-API-KEY


# - Prompt -

# Digunakan to_category.py untuk menetapkan prompt_template di bawah sebagai 
# kategori apa. Jika jawaban AI terdaftar maka field category akan diisi dengan
# nilai pertama yaitu "laptop".
# Sifatnya wajib.
category = laptop, notebook

# Hanya tanya ke AI bila sesuai filter. Selain itu akan ditetapkan ke kategori
# "lainnya". Filter ini digunakan oleh DataFrame.query().
# Bila di filter ditemukan "stock > 0" maka downloader.py hanya akan membaca
# yang ada stoknya saja.
# Sifatnya tidak wajib.
filter = stock > 0

# {desc} akan diganti dengan gabungan field title dan description.
# Sifatnya wajib.
prompt_template =
    Berikut ini spesifikasi hardware.

    {desc}

    Jawab pertanyaan berikut dalam bentuk JSON dictionary sesuai nomor urut.

    {columns}


# Nama kolom dan pertanyaan untuk AI. Rangkaian ini akan disematkan di
# {columns} pada prompt_template di atas.
# Sifatnya wajib.
columns =
    category: Apakah ini sebuah laptop atau lainnya ? Jawab singkat.
    brand_name: Apa mereknya ? Satu kata saja.
    processor: Kalimat mana yang menunjukkan processor ?
    processor_name: Apa brand prosesornya ? Satu kata saja.
    graphic: Kalimat mana yang menunjukkan graphic adapter ?
    graphic_gb: Memori graphic adapter berapa gigabyte ? Sebut angka saja.
    graphic_name: Apa brand graphic adaptor-nya ? Satu kata saja.
    memory: Kalimat mana yang menunjukkan kapasitas memori ?
    memory_gb: Memori berapa gigabyte ? Sebut angka saja.
    storage: Kalimat mana yang menunjukkan kapasitas storage ?
    storage_gb: Storage berapa gigabyte ? Sebut angka saja.
    monitor: Kalimat mana yang menunjukkan ukuran monitor ?
    monitor_inch: Monitornya berapa inchi ? Sebut angka saja.
    is_touchscreen: Kalimat mana yang menunjukkan touchscreen ?
    weight: Kalimat mana yang menunjukkan berat ?
    weight_kg: Beratnya berapa kilogram ? Sebut angka saja.


# ---------
# repair.py
# ---------

# Sebuah laptop wajib ada informasi processor. Jika tidak ada maka akan
# ditetapkan sebagai kategori "lainnya".
# Sifatnya tidak wajib.
not_null_columns =
    processor


# - Numeric -

# Jika nama kolom berakhiran underscore ( _ ) ditambah numeric unit (contoh:
# memory_gb) maka nilainya akan diuji dengan fungsi float(). Jika gagal maka
# diganti dengan None. 
# Sifatnya tidak wajib.
numeric_units =
    gb
    inch
    kg


# Jika nilainya di luar batas maka akan dikosongkan
range_values =
    monitor_inch:7,20
    graphic_gb:1,32
    weight_kg:0.5,10


# --------
# check.py
# --------

# Menjalankannya tidaklah wajib. Ini membantu kita memeriksa kebenaran data.

# Daftar kolom yang akan dihitung jumlah produknya:
# SELECT column, count(*) FROM ... GROUP BY 1
count_columns =
    brand_name
    processor_name
    graphic_name
    memory_gb
    storage_gb
    graphic_gb
    monitor_inch

# Daftar kolom yang akan dihitung nilai minimum dan maksimumnya:
# SELECT column, min(column), max(column) FROM ... GROUP BY 1
min_max_columns =
    weight_kg
    price


# - Name -

# Nama kolom yang berakhiran "_name" nilainya akan dicek berdasarkan daftar
# ini. Misalkan AI menetapkan brand_name = MacBook maka repair.py mengubahnya
# menjadi Apple. Ia juga peduli huruf kecil dan besar. Jadi bila AI bilang
# brand_name = LENOVO maka akan diubah menjadi Lenovo. Untuk ASUS tidak berubah
# sesuai yang terdaftar.

[brand_name]
Apple =
    MacBook
ASUS =
Dell =
    Latitude
Lenovo =
Zyrex =
    Maveric


[processor_name]
AMD =
    Ryzen
Apple =
    M2
    M2 PRO
    M3
    M3 PRO
    M4
Qualcomm =
    Snapdragon


[graphic_name]
AMD =
    Vega
    Radeon
Apple =
    M2
    M3
Intel =
    HD
    Integrated
    IRIS
    UHD
    UMA
NVIDIA =
    GeForce
    RTX
Qualcomm =
    Adreno
