[main]
category = laptop
base_download_dir = /home/sugiana/tmp
ollama_url = http://localhost:11434
ollama_model = gemma2

# gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent 
# gemini_key = YOUR-API-KEY

url =
    https://www.tokopedia.com/nvidiageforcelt/product
    https://www.tokopedia.com/lenovojakarta/product
    https://www.tokopedia.com/dell-premium-official/product
    https://www.tokopedia.com/dellflagship/product
    https://www.tokopedia.com/asus/product
    https://macstore.id/product-category/macbook
    https://www.tokopedia.com/msi-official/product
    https://www.tokopedia.com/hp/etalase/semua-laptop
    https://www.tokopedia.com/acer-jakarta/product
    https://www.tokopedia.com/axioo-indonesia/product
    https://www.tokopedia.com/zyrex/product
    https://www.tokopedia.com/glorycomputerr/product
