[main]
# ---------------
# HTML DOWNLOADER
# ---------------

# Digunakan crawler.py. Jika tidak ditetapkan maka akan dibuat direktori "tmp"
# di home.
;base_download_dir = /home/sugiana/tmp

# Digunakan downloader.py berisi daftar tautan produk sesuai kategori. Jika di
# antaranya memuat produk lain seperti plastik bubble atau kotak kayu maka akan
# ditetapkan oleh AI sebagai kategori "lainnya". Jadi tidak masalah tercampur.
# Sifatnya wajib.
url =
    https://www.tokopedia.com/tokorytech/etalase/esp32-nodemcu-iot
    https://www.tokopedia.com/electracore-id/etalase/esp32
    https://www.tokopedia.com/electracore-id/etalase/esp8266
    https://www.tokopedia.com/mechatron/etalase/esp
    https://www.tokopedia.com/easyware-id/etalase/arduino-development-board
    https://www.tokopedia.com/easyware-id/etalase/raspberry-pi-development-board
    https://www.tokopedia.com/easyware-id/etalase/wemos-development-board
    https://www.tokopedia.com/easyware-id/etalase/development-board
    https://www.tokopedia.com/easyware-id/etalase/all?q=esp32


# ------------
# AKAL IMITASI
# ------------

# - Prompt -

# Digunakan to_category.py untuk menetapkan prompt_template di bawah sebagai 
# kategori apa. Jika jawaban AI terdaftar maka field category akan diisi dengan
# nilai pertama yaitu "gpu".
# Sifatnya wajib.
category = mcu, microcontroller

# Hanya tanya ke AI bila sesuai filter. Selain itu akan ditetapkan ke kategori
# "lainnya". Filter ini digunakan oleh DataFrame.query().
# Bila di filter ditemukan "stock > 0" maka downloader.py hanya akan membaca
# yang ada stoknya saja.
# Sifatnya tidak wajib.
filter = stock > 0

# {desc} akan diganti dengan gabungan field title dan description.
# Sifatnya wajib.
prompt_template =
    Berikut ini spesifikasi hardware.

    {desc}

    Jawab pertanyaan berikut dalam bentuk JSON dictionary sesuai nomor urut.

    {columns}


# Nama kolom dan pertanyaan untuk AI. Rangkaian ini akan disematkan di
# {columns} pada prompt_template di atas.
# Sifatnya wajib.
columns =
    category: Apakah ini sebuah microcontroller atau lainnya ? Jawab singkat.
    brand_name: Apa mereknya ? Satu kata saja.
    usb: Kalimat mana yang menunjukkan jenis USB ?
    is_usb_c: Kalimat mana yang menunjukkan USB type-C ?
    is_charger: Kalimat mana yang menunjukkan kemampuan untuk mengisi baterai ?


# --------
# check.py
# --------

# Daftar kolom yang akan dihitung jumlah produknya:
# SELECT column, count(*) FROM ... GROUP BY 1
count_columns =
    brand_name
    is_usb_c
    is_charger


# - Name -

# Nama kolom yang berakhiran "_name" nilainya akan dicek berdasarkan daftar
# ini. Misalkan AI menetapkan brand_name = GeForce maka repair.py mengubahnya
# menjadi NVIDIA. Ia juga peduli huruf kecil dan besar. Jadi bila AI bilang
# brand_name = GIGABYTE maka akan diubah menjadi Gigabyte. Untuk ASUS tidak berubah
# sesuai yang terdaftar.

[brand_name]
ESP32 =
ESP8266 =
