[main]
# ---------------
# HTML DOWNLOADER
# ---------------

# Digunakan crawler.py. Jika tidak ditetapkan maka akan dibuat direktori "tmp"
# di home.
;base_download_dir = /home/sugiana/tmp

# Digunakan downloader.py berisi daftar tautan produk sesuai kategori. Jika di
# antaranya memuat produk lain seperti plastik bubble atau kotak kayu maka akan
# ditetapkan oleh AI sebagai kategori "lainnya". Jadi tidak masalah tercampur.
# Sifatnya wajib.
url =
    https://www.tokopedia.com/gigabyteofficial/etalase/amd-motherboard
    https://www.tokopedia.com/gigabyteofficial/etalase/intel-motherboard
    https://www.tokopedia.com/asus-component/etalase/motherboard-amd
    https://www.tokopedia.com/asus-component/etalase/motherboard-intel
    https://www.tokopedia.com/msi-id/etalase/amd-motherboard
    https://www.tokopedia.com/msi-id/etalase/intel-motherboard
    https://www.tokopedia.com/aofficial-14/etalase/motherboard-amd
    https://www.tokopedia.com/aofficial-14/etalase/motherboard-intel
    https://www.tokopedia.com/biostarsme/etalase/biostar-mb


# ------------
# AKAL IMITASI
# ------------

# Hal AI digunakan oleh to_category.py.

# Ini adalah "system prompt" yang mengawali "user prompt". Saat ini hanya
# digunakan oleh Ollama.
;role =
;    Kamu adalah seorang yang pendiam. Jawabanmu selalu singkat dan tanpa
;    asesoris kata seperti tambahan 2 karakter bintang ( ** ) untuk menebalkan,
;    dan sejenisnya


# - AI: Ollama -

# Digunakan to_category.py, berisi tautan web service Ollama
ollama_url = http://localhost:11434/api/chat

# Model Ollama yang digunakan. Daftarnya bisa lihat dengan perintah "ollama list".
ollama_model = gemma2


# - AI: Gemini -

# Tautan web service Gemini. Jika ini aktif maka konfigurasi Ollama diabaikan.
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-thinking-exp-01-21:generateContent?key=YOUR-API-KEY


# - Prompt -

# Digunakan to_category.py untuk menetapkan prompt_template di bawah sebagai 
# kategori apa. Jika jawaban AI terdaftar maka field category akan diisi dengan
# nilai pertama yaitu "mobo".
# Sifatnya wajib.
category = mobo, motherboard

# Hanya tanya ke AI bila sesuai filter. Selain itu akan ditetapkan ke kategori
# "lainnya". Filter ini digunakan oleh DataFrame.query().
# Bila di filter ditemukan "stock > 0" maka downloader.py hanya akan membaca
# yang ada stoknya saja.
# Sifatnya tidak wajib.
filter = stock > 0

# {desc} akan diganti dengan gabungan field title dan description.
# Sifatnya wajib.
prompt_template =
    Berikut ini spesifikasi hardware.

    {desc}

    Jawab pertanyaan berikut dalam bentuk JSON dictionary sesuai nomor urut.

    1. Apakah ini sebuah motherboard komputer atau lainnya ? Jawab singkat.

    Jika motherboard maka lanjut jawab ini:

    2. Apa mereknya ? Satu kata saja.
    3. Kalimat mana yang menunjukkan PCIe tipe x16 ?
    4. Ada berapa PCIe tipe x16 ? Sebut angka saja.
    5. Versi berapa PCIe tipe x16 ? Sebut angka saja.


# Urutan kolom sesuai prompt_template.
# Sifatnya wajib.
columns =
    category
    brand_name
    pcie_x16
    pcie_x16_count
    pcie_x16_version


# ---------
# repair.py
# ---------

# Sebuah motherboard wajib ada informasi PCIe x16 sebagai tempat GPU. Jika
# tidak ada maka akan ditetapkan sebagai kategori "lainnya".
# Sifatnya tidak wajib.
not_null_columns =
    pcie_x16


# - Numeric -

# Jika nama kolom berakhiran underscore ( _ ) ditambah numeric unit (contoh:
# pcie_x16_count) maka nilainya akan diuji dengan fungsi float(). Jika gagal maka
# diganti dengan None. 
# Sifatnya tidak wajib.
numeric_units =
    count
    version


# Jika nilainya di luar batas maka akan dikosongkan
range_values =
    pcie_x16_count:1,8
    pcie_x16_version:1,5


# --------
# check.py
# --------

# Daftar kolom yang akan dihitung jumlah produknya:
# SELECT column, count(*) FROM ... GROUP BY 1
count_columns =
    brand_name
    pcie_x16_version
    pcie_x16_count


# Daftar kolom yang akan dihitung nilai minimum dan maksimumnya:
# SELECT column, min(column), max(column) FROM ... GROUP BY 1
min_max_columns =
    price
