[main]
# ---------------
# HTML DOWNLOADER
# ---------------

# Digunakan crawler.py. Jika tidak ditetapkan maka akan dibuat direktori "tmp"
# di home.
;base_download_dir = /home/sugiana/tmp

# Digunakan downloader.py berisi daftar tautan produk sesuai kategori. Jika di
# antaranya memuat produk lain seperti plastik bubble atau kotak kayu maka akan
# ditetapkan oleh AI sebagai kategori "lainnya". Jadi tidak masalah tercampur.
# Sifatnya wajib.
url =
    https://www.tokopedia.com/agreskomputerofficial/etalase/agres-pyrolite-mid-gaming-amd
    https://www.tokopedia.com/agreskomputerofficial/etalase/agres-cryo-high-end-gaming-intel
    https://www.tokopedia.com/agreskomputerofficial/etalase/agres-titan-ultimate-gaming
    https://www.tokopedia.com/star-seventeen-com/etalase/gaming-ai-editing-render-server-pc
    https://www.tokopedia.com/onelinegamepc/etalase/pc-rakitan


# ------------
# AKAL IMITASI
# ------------

# - Prompt -

# Digunakan to_category.py untuk menetapkan prompt_template di bawah sebagai 
# kategori apa. Jika jawaban AI terdaftar maka field category akan diisi dengan
# nilai pertama yaitu "pc".
# Sifatnya wajib.
category = pc

# Hanya tanya ke AI bila sesuai filter. Selain itu akan ditetapkan ke kategori
# "lainnya". Filter ini digunakan oleh DataFrame.query().
# Bila di filter ditemukan "stock > 0" maka downloader.py hanya akan membaca
# yang ada stoknya saja.
# Sifatnya tidak wajib.
filter = stock > 0

# {desc} akan diganti dengan gabungan field title dan description.
# Sifatnya wajib.
prompt_template =
    Berikut ini spesifikasi hardware.

    {desc}

    Jawab pertanyaan berikut dalam bentuk JSON dictionary sesuai nomor urut.

    {columns}


# Nama kolom dan pertanyaan untuk AI. Rangkaian ini akan disematkan di
# {columns} pada prompt_template di atas.
# Sifatnya wajib.
columns =
    category: Apakah ini sebuah PC atau lainnya ? Jawab singkat.
    brand_name: Apa mereknya ? Satu kata saja.
    processor: Kalimat mana yang menunjukkan processor ?
    processor_name: Apa brand prosesornya ? Satu kata saja.
    graphic: Kalimat mana yang menunjukkan graphic adapter ?
    graphic_gb: Memori graphic adapter berapa gigabyte ? Sebut angka saja.
    graphic_name: Apa brand processor graphic adaptor-nya ? Satu kata saja. Kalau GEFORCE berarti NVIDIA.
    memory: Kalimat mana yang menunjukkan kapasitas memori ?
    memory_gb: Memori berapa gigabyte ? Sebut angka saja.
    storage: Kalimat mana yang menunjukkan kapasitas storage ?
    storage_gb: Storage berapa gigabyte ? Sebut angka saja.


# ---------
# repair.py
# ---------

# Sebuah PC wajib ada informasi processor dan graphic. Jika tidak ada maka akan
# ditetapkan sebagai kategori "lainnya".
# Sifatnya tidak wajib.
not_null_columns =
    processor
    graphic


# - Numeric -

# Jika nama kolom berakhiran underscore ( _ ) ditambah numeric unit (contoh:
# memory_gb) maka nilainya akan diuji dengan fungsi float(). Jika gagal maka
# diganti dengan None. 
# Sifatnya tidak wajib.
numeric_units =
    gb


# Jika nilainya di luar batas maka akan dikosongkan
range_values =
    graphic_gb:1,64


# --------
# check.py
# --------

# Menjalankannya tidaklah wajib. Ini membantu kita memeriksa kebenaran data.

# Daftar kolom yang akan dihitung jumlah produknya:
# SELECT column, count(*) FROM ... GROUP BY 1
count_columns =
    brand_name
    processor_name
    graphic_name
    memory_gb
    storage_gb
    graphic_gb

# Daftar kolom yang akan dihitung nilai minimum dan maksimumnya:
# SELECT column, min(column), max(column) FROM ... GROUP BY 1
min_max_columns =
    price


# - Name -

# Nama kolom yang berakhiran "_name" nilainya akan dicek berdasarkan daftar
# ini. Misalkan AI menetapkan brand_name = MacBook maka repair.py mengubahnya
# menjadi Apple. Ia juga peduli huruf kecil dan besar. Jadi bila AI bilang
# brand_name = LENOVO maka akan diubah menjadi Lenovo. Untuk ASUS tidak berubah
# sesuai yang terdaftar.

[brand_name]
Apple =
    MacBook
ASUS =
Dell =
    Latitude
Lenovo =
Zyrex =
    Maveric


[processor_name]
AMD =
    Ryzen
Apple =
    M2
    M2 PRO
    M3
    M3 PRO
    M4
Qualcomm =
    Snapdragon


[graphic_name]
AMD =
    Vega
    Radeon
Apple =
    M2
    M3
Intel =
    HD
    Integrated
    IRIS
    UHD
    UMA
NVIDIA =
    GeForce
    RTX
Qualcomm =
    Adreno
