[main]
url =
    https://www.tokopedia.com/coolermaster-id/etalase/power-supplies
    https://www.tokopedia.com/thermaltake/etalase/psu
    https://www.tokopedia.com/enterkomputer/etalase/power-supply
    https://www.tokopedia.com/corsair-official-store/etalase/psu
    https://www.tokopedia.com/asus-component/etalase/psu
    https://www.tokopedia.com/nanokomputer/etalase/psu
    https://www.tokopedia.com/nanokomputer/etalase/pcie-5-psu
    https://www.tokopedia.com/nanokomputer/etalase/sfx-psu
    https://www.tokopedia.com/enterkomputer/etalase/power-supply

ollama_url = http://localhost:11434/api/chat
ollama_model = gemma2

category = psu, power supply unit

filter = stock > 0

prompt_template =
    Berikut ini spesifikasi hardware.

    {desc}

    Jawab pertanyaan berikut dalam bentuk JSON dictionary sesuai nomor urut.

    {columns}


# Nama kolom dan pertanyaan untuk AI. Rangkaian ini akan disematkan di
# {columns} pada prompt_template di atas.
columns =
    category: Apakah ini sebuah power supply unit (PSU) atau lainnya ? Jawab singkat.
    brand_name: Apa mereknya ? Satu kata saja.
    power_watt: Berapa watt ? Sebut angka saja.
    model_name: Modelnya platinum, gold, atau lainnya ? Satu kata saja.


# ---------
# repair.py
# ---------

# Sebuah power supply unit (PSU) wajib ada kapasitas watt-nya. Jika tidak ada
# maka akan ditetapkan sebagai kategori "lainnya".
not_null_columns =
    power_watt


# - Numeric -

# Jika nama kolom berakhiran underscore ( _ ) ditambah numeric unit (contoh:
# power_watt) maka nilainya akan diuji dengan fungsi float(). Jika gagal maka
# diganti dengan None. 
numeric_units =
    watt


# Jika nilainya di luar batas maka akan dikosongkan
range_values =
    power_watt:50,10000
 

# --------
# check.py
# --------

# Menjalankannya tidaklah wajib. Ini membantu kita memeriksa kebenaran data.

# Daftar kolom yang akan dihitung jumlah produknya:
# SELECT column, count(*) FROM ... GROUP BY 1
count_columns =
    brand_name
    model_name
    power_watt

# Daftar kolom yang akan dihitung nilai minimum dan maksimumnya:
# SELECT column, min(column), max(column) FROM ... GROUP BY 1
min_max_columns =
    power_watt
    price
