[main]
# ---------------
# HTML DOWNLOADER
# ---------------

# Digunakan crawler.py. Jika tidak ditetapkan maka akan dibuat direktori "tmp"
# di home.
;base_download_dir = /home/sugiana/tmp

# Digunakan downloader.py berisi daftar tautan produk sesuai kategori. Jika di
# antaranya memuat produk lain seperti plastik bubble atau kotak kayu maka akan
# ditetapkan oleh AI sebagai kategori "lainnya". Jadi tidak masalah tercampur.
# Sifatnya wajib.
url =
    https://www.tokopedia.com/samsungmemory/etalase/internal-ssd
    https://www.tokopedia.com/seagate/etalase/barracuda-ssd
    https://www.tokopedia.com/seagate/etalase/firecuda-ssd
    https://www.tokopedia.com/seagate/etalase/nytro-ssd
    https://www.tokopedia.com/seagate/etalase/ironwolf-ssd


# ------------
# AKAL IMITASI
# ------------

# Hal AI digunakan oleh to_category.py.

# Ini adalah "system prompt" yang mengawali "user prompt". Tujuannya untuk
# mendapatkan jawaban yang lebih tepat. Saat ini hanya digunakan oleh Ollama.
# Sifatnya tidak wajib.
;role =
;    Kamu adalah seorang yang pendiam. Jawabanmu selalu singkat dan tanpa
;    asesoris kata seperti tambahan 2 karakter bintang ( ** ) untuk menebalkan,
;    dan sejenisnya


# - AI: Ollama -

# Digunakan to_category.py, berisi tautan web service Ollama.
# Sifatnya tidak wajib jika gemini_url aktif.
ollama_url = http://localhost:11434/api/chat
ollama_model = gemma2


# - AI: Gemini -

# Tautan web service Gemini. Jika ini aktif maka ollama_url diabaikan.
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-thinking-exp-01-21:generateContent?key=YOUR-API-KEY


# - Prompt -

# Digunakan to_category.py untuk menetapkan prompt_template di bawah sebagai 
# kategori apa. Jika jawaban AI terdaftar maka field category akan diisi dengan
# nilai pertama yaitu "storage".
# Sifatnya wajib.
category = storage, penyimpanan


# Hanya tanya ke AI bila sesuai filter. Selain itu akan ditetapkan ke kategori
# "lainnya". Filter ini digunakan oleh DataFrame.query().
# Bila di filter ditemukan "stock > 0" maka downloader.py hanya akan membaca
# yang ada stoknya saja. Untuk storage sebaiknya gunakan yang baru.
# Sifatnya tidak wajib.
filter = stock > 0 and is_new == 1

# {desc} akan diganti dengan gabungan field title dan description.
# Sifatnya wajib.
prompt_template =
    Berikut ini spesifikasi hardware.

    {desc}

    Jawab pertanyaan berikut dalam bentuk JSON dictionary sesuai nomor urut.

    1. Apakah ini sebuah storage atau lainnya ? Jawab singkat.

    Jika storage maka lanjut jawab ini:

    2. Apa mereknya ? Satu kata saja.
    3. Berapa gigabyte kapasitasnya ? Sebut angka saja.
    4. PCIe versi berapa ? Sebut angka saja.
    5. Berapa tahun garansinya ? Sebut angka saja.


# Urutan kolom sesuai prompt_template.
# Sifatnya wajib.
columns =
    category
    brand_name
    capacity_gb
    pcie_version
    warranty_year


# ---------
# repair.py
# ---------

# Sebuah storage wajib ada informasi merek. Jika tidak ada maka akan
# ditetapkan sebagai kategori "lainnya".
# Sifatnya tidak wajib.
not_null_columns =
    brand_name
    capacity_gb


# - Numeric -

# Jika nama kolom berakhiran underscore ( _ ) ditambah numeric unit (contoh:
# memory_gb) maka nilainya akan diuji dengan fungsi float(). Jika gagal maka
# diganti dengan None. 
# Sifatnya tidak wajib.
numeric_units =
    gb
    version
    year


# Jika nilainya di luar batas maka akan dikosongkan
range_values =
    pcie_version:1,5
    warranty_year:1,20


# --------
# check.py
# --------

# Menjalankannya tidaklah wajib. Ini membantu kita memeriksa kebenaran data.

# Daftar kolom yang akan dihitung jumlah produknya:
# SELECT column, count(*) FROM ... GROUP BY 1
count_columns =
    brand_name
    capacity_gb
    warranty_year
    pcie_version

# Daftar kolom yang akan dihitung nilai minimum dan maksimumnya:
# SELECT column, min(column), max(column) FROM ... GROUP BY 1
min_max_columns =
    capacity_gb
    pcie_version
    price


# - Name -

# Nama kolom yang berakhiran "_name" nilainya akan dicek berdasarkan daftar
# ini. Misalkan AI menetapkan brand_name = Asustor maka repair.py mengubahnya
# menjadi Seagate. Ia juga peduli huruf kecil dan besar. Jadi bila AI bilang
# brand_name = SEAGATE maka akan diubah menjadi Seagate.

[brand_name]
Seagate =
    Asustor
    Lacie
    Synology
