[main]
# ---------------
# HTML DOWNLOADER
# ---------------

# Digunakan crawler.py. Jika tidak ditetapkan maka akan dibuat direktori "tmp"
# di home.
;base_download_dir = /home/sugiana/tmp

# Digunakan downloader.py berisi daftar tautan produk sesuai kategori. Jika di
# antaranya memuat produk lain seperti plastik bubble atau kotak kayu maka akan
# ditetapkan oleh AI sebagai kategori "lainnya". Jadi tidak masalah tercampur.
url =
    https://www.tokopedia.com/samsung-official-store/etalase/tablets
    https://macstore.id/product-category/ipad
    https://www.tokopedia.com/xiaomi/etalase/tablet
    https://www.tokopedia.com/advanstore/etalase/tablet
    https://www.tokopedia.com/royalgadgetstore/product
    https://www.tokopedia.com/studioponsel/etalase/apple-ipad
    https://www.tokopedia.com/onestopgaming/etalase/surface
    https://www.tokopedia.com/oppo/product


# ------------
# AKAL IMITASI
# ------------

# Hal AI digunakan oleh to_category.py.

# Ini adalah "system prompt" yang mengawali "user prompt". Saat ini hanya
# digunakan oleh Ollama.
;role =
;    Kamu adalah seorang yang pendiam. Jawabanmu selalu singkat dan tanpa
;    asesoris kata seperti tambahan 2 karakter bintang ( ** ) untuk menebalkan,
;    dan sejenisnya


# - AI: Ollama -

# Digunakan to_category.py, berisi tautan web service Ollama
ollama_url = http://localhost:11434/api/chat

# Model Ollama yang digunakan.
ollama_model = gemma2


# - AI: Gemini -

# Tautan web service Gemini. Jika ini aktif maka konfigurasi Ollama diabaikan.
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=YOUR-API-KEY
;gemini_url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-thinking-exp-01-21:generateContent?key=YOUR-API-KEY


# - Prompt -

# Digunakan to_category.py untuk menetapkan prompt_template di bawah sebagai 
# kategori apa. Jika jawaban AI terdaftar maka field category akan diisi dengan
# nilai pertama yaitu "tablet".
# Sifatnya wajib.
category = tablet, pad 

# Hanya tanya ke AI bila sesuai filter. Selain itu akan ditetapkan ke kategori
# "lainnya". Filter ini digunakan oleh DataFrame.query().
# Bila di filter ditemukan "stock > 0" maka downloader.py hanya akan membaca
# yang ada stoknya saja.
# Sifatnya tidak wajib.
filter = stock > 0

# {desc} akan diganti dengan gabungan field title dan description.
# Sifatnya wajib.
prompt_template =
    Berikut spesifikasi hardware.

    {desc}

    Jawab pertanyaan berikut dalam bentuk JSON dictionary sesuai nomor urut.

    {columns}


# Nama kolom dan pertanyaan untuk AI. Rangkaian ini akan disematkan di
# {columns} pada prompt_template di atas.
columns =
    category: Apakah ini kategorinya tablet, handphone, laptop, atau lainnya ? Jawab singkat saja.
    brand_name: Apa mereknya ? Satu kata saja.
    processor: Kalimat mana yang menunjukkan CPU ?
    processor_name: Apa brand prosesornya ? Satu kata saja.
    graphic: Kalimat mana yang menunjukkan graphic adapter ?
    graphic_name: Apa brand graphic adaptor-nya ? Satu kata saja.
    memory: Kalimat mana yang menunjukkan RAM ? Singkat saja.
    memory_gb: RAM berapa gigabyte ? Sebut angka saja.
    storage: Kalimat mana yang menunjukkan kapasitas storage ?
    storage_gb: Storage berapa gigabyte ? Sebut angka saja.
    monitor: Kalimat mana yang menunjukkan ukuran monitor ?
    monitor_inch: Monitornya berapa inch ? Sebut angka saja.
    usb: Kalimat mana yang menunjukkan jenis USB ?
    is_usb_c: Kalimat mana yang menunjukkan USB type-C ?
    battery: Kalimat mana yang menunjukkan kapasitas baterai ?
    battery_mah: Baterainya berapa mAh ? Sebut angka saja.
    weight: Kalimat mana yang menunjukkan berat ?
    weight_kg: Beratnya berapa kilogram ? Sebut angka saja.
    camera: Kalimat mana yang menunjukkan fitur kamera ?
    camera_mp: Kameranya berapa mega pixel ? Sebut angka saja.
    camera_aperture: Aperture-nya berapa ? Biasanya tertulis f/n, sebutkan nilai n saja.
    is_pencil: Kalimat mana yang menunjukkan pensil ?


# ---------
# repair.py
# ---------

# Sebuah tablet wajib ada informasi processor. Jika tidak ada maka akan
# ditetapkan sebagai kategori "lainnya".
# Sifatnya tidak wajib.
not_null_columns =
    processor

# - Numeric -

# Jika nama kolom berakhiran underscore ( _ ) ditambah numeric unit (contoh:
# memory_gb) maka nilainya akan diuji dengan fungsi float(). Jika gagal maka
# diganti dengan None. 
numeric_units =
    gb
    inch
    mah
    kg
    mp
    aperture


# Jika nilainya di luar batas maka akan dikosongkan
range_values =
    memory_gb:1,128
    storage_gb:16,2048
    monitor_inch:7.01,12
    battery_mah:1,99999
    camera_mp:1,999
    camera_aperture:1,22


# --------
# check.py
# --------

# Daftar kolom yang akan dihitung jumlah produknya:
# SELECT column, count(*) FROM ... GROUP BY 1
count_columns =
    brand_name
    processor_name
    graphic_name
    memory_gb
    storage_gb
    monitor_inch
    battery_mah
    camera_mp
    camera_aperture


# Daftar kolom yang akan dihitung nilai minimum dan maksimumnya:
# SELECT column, min(column), max(column) FROM ... GROUP BY 1
min_max_columns =
    memory_gb
    storage_gb
    weight_kg
    price
